title: You Need Sex

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://youneedsex.com"

timezone: Asia/Shanghai
encoding: utf-8

collections:
  essays:
    output: true
    permalink: /:collection/:name
  movies:
    output: true
    permalink: /:collection/:year/:name
  books:
    output: true
    permalink: /:collection/:year/:name

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "page"
  -
    scope:
      path: "_movies"
      type: movies
    values:
      categories: [movies]
      layout: "post"
  -
    scope:
      path: "_books"
      type: books
    values:
      categories: [books]
      layout: "post"
  -
    scope:
      type: "essays"
    values:
      layout: "post"
      author: "深井兵太郎"

plugins:
  - jekyll-seo-tag

sass:
  sass_dir: _sass/
  style: compressed

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: []
