title: 阅读理解

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yuedulijie.com"

timezone: Asia/Shanghai
encoding: utf-8

collections:
  essays:
    output: true
    permalink: /:collection/:name

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "page"
  -
    scope:
      type: "essays"
    values:
      layout: "post"
      author: "浅井兵太郎"

sass:
  sass_dir: _sass/
  style: compressed

compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: []
